--- FAIL: TestSchemaString (0.00s)
    --- FAIL: TestSchemaString/field-with-id-directive.graphql (0.00s)
        schemagen_test.go:84: 
            	Error Trace:	schemagen_test.go:84
            	Error:      	Received unexpected error:
            	            	input:38: Cannot redeclare directive auth.
            	Test:       	TestSchemaString/field-with-id-directive.graphql
